forkilla/urls.py
from django.conf.urls import url
from . import views

listOfAddresses = ['localhost:8000', 'sd2019-forkillaa1.herokuapp.com', 'sd2019-forkillaa7.herokuapp.com']

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^restaurants/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/(?P<category>.*)$', views.restaurants, name='restaurants'),
    url(r'^restaurant/(?P<restaurant_number>.*)/', views.restaurant, name='restaurant'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^reservations/$', views.reservations, name='reservations'),
    url(r'^comparator/$', views.comparator, {'ips': listOfAddresses}, name='comparator'),
]

forkilla/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


class Restaurant(models.Model):

    CATEGORIES = (
        ("Rice", "Rice"),
        ("Fusi", "Fusion"),
        ("BBQ", "Barbecue"),
        ("Chin", "Chinese"),
        ("Medi","Mediterranean"),
        ("Crep","Creperie"),
        ("Hind","Hindu"),
        ("Japa","Japanese"),
        ("Ital","Italian"),
        ("Mexi","Mexican"),
        ("Peru", "Peruvian"),
        ("Russ","Russian"),
        ("Turk","Turkish"),
        ("Basq","Basque"),
        ("Vegy", "Vegetarian"),
        ("Afri","African"),
        ("Egyp","Egyptian"),
        ("Grek","Greek")
    )

    _d_categories = dict(CATEGORIES)

    restaurant_number = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=50)
    menu_description = models.TextField()
    price_average = models.DecimalField(max_digits=5, decimal_places=2)
    is_promot = models.BooleanField()
    rate = models.DecimalField(max_digits=3, decimal_places=1)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    featured_photo = models.ImageField(upload_to="photos")
    category = models.CharField(max_length=5, choices=CATEGORIES)
    capacity = models.PositiveIntegerField()

    def get_human_category(self):
        return self._d_categories[self.category]

    def __str__(self):
        return ('[**Promoted**]' if self.is_promot else '') + "[" + self.category + "] " \
                "[" + self.restaurant_number + "] " + self.name + " - " + self.menu_description + " (" + str(self.rate) + ")" \
                ": " + str(self.price_average) + u" €"

class Reservation(models.Model):

    SLOTS = (
        ("morning_first", "12h00"),
        ("morning_second", "13h00"),
        ("morning_third", "14h00"),
        ("morning_fourth", "15h00"),
        ("evening_first", "20h00"),
        ("evening_second", "21h00"),
        ("evening_third", "22h00"),
    )
    _d_slots = dict(SLOTS)
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    day = models.DateField(default=datetime.now)
    time_slot = models.CharField(max_length=15, choices=SLOTS)
    num_people = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])

    def get_human_slot(self):
        return self._d_slots[self.time_slot]

class Review(models.Model):
    message = models.CharField(max_length=200)
    rating = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Pick(models.Model):

   CITIES = (
      ("barcelona", "Barcelona"),
      ("madrid", "Madrid"),
      ("paris", "Paris"),
      ("chicago", "Chicago"),
      ("ny", "New York City"),
      ("toronto", "Toronto"),
      ("london", "London"),
   )

   _d_cities = dict(CITIES)

   CATEGORIES = (
      (" ", "Anything"),
      ("Rice", "Rice"),
      ("Fusi", "Fusion"),
      ("BBQ", "Barbecue"),
      ("Chin", "Chinese"),
      ("Medi","Mediterranean"),
      ("Crep","Creperie"),
      ("Hind","Hindu"),
      ("Japa","Japanese"),
      ("Ital","Italian"),
      ("Mexi","Mexican"),
      ("Peru", "Peruvian"),
      ("Russ","Russian"),
      ("Turk","Turkish"),
      ("Basq","Basque"),
      ("Vegy", "Vegetarian"),
      ("Afri","African"),
      ("Egyp","Egyptian"),
      ("Grek","Greek")
   )

   category = models.CharField(max_length=5, choices=CATEGORIES)
   city = models.CharField(max_length=10, choices=CITIES)

class ComparatorData(models.Model):

   category = models.CharField(max_length=50)
   city = models.CharField(max_length=50)
   price_average = models.DecimalField(max_digits=5, decimal_places=2)

class ViewedRestaurants(models.Model):
   id_vr = models.AutoField(primary_key=True)
   restaurant = models.ManyToManyField(Restaurant, through='RestaurantInsertDate')

class RestaurantInsertDate(models.Model):
    viewedrestaurants = models.ForeignKey(ViewedRestaurants, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added']

forkilla/forms.py
from django import forms
from .models import Reservation, Pick, Review, ComparatorData

class PickerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(PickerForm, self).__init__(*args, **kwargs)
        self.fields['category'].label = "I want to eat "
        self.fields['city'].label = " in "

    class Meta:
        model = Pick
        fields = ["category", "city"]

class ReservationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields['num_people'].label = "Number of people"

    class Meta:
        model = Reservation
        fields = ["day", "time_slot", "num_people"]

class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ["message", "rating"]

class ComparatorForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(ComparatorForm, self).__init__(*args, **kwargs)
        self.fields['price_average'].label = "Maximum price"

    class Meta:
        model = ComparatorData
        fields = ["city", "category", "price_average"]

forkilla/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Restaurant, ViewedRestaurants, RestaurantInsertDate, Review, Reservation
from .forms import ReservationForm, PickerForm, ReviewForm, ComparatorForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import RestaurantSerializer,UsersSerializer
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.decorators import api_view

def index(request):
    promoted_restaurants =  Restaurant.objects.filter()
    categories = Restaurant._d_categories
    viewedrestaurants = _check_session(request)

    if request.method == "POST":
        form = PickerForm(request.POST)
        if form.is_valid():
                data = form.cleaned_data

        return HttpResponseRedirect(reverse('restaurants', args=[data['city'], data['category']]))

    context = {
        'restaurants': promoted_restaurants,
        'viewedrestaurants': viewedrestaurants,
        'form': PickerForm(label_suffix='', initial={'category': 'Medi', 'city': 'barcelona'})
    }

    return render(request, 'forkilla/index.html', context)

def restaurants(request, city="", category=""):

    promoted = False
    human_category = None

    categories = Restaurant._d_categories
    viewedrestaurants = _check_session(request)

    try:
        human_category = categories[category.capitalize()]
    except KeyError:
        pass

    if city and human_category:
        restaurants_by_city = Restaurant.objects.filter(city__iexact=city, category__iexact=category)

    else:
        if city:
            restaurants_by_city = Restaurant.objects.filter(city__iexact=city)
        else:
            restaurants_by_city =  Restaurant.objects.filter(is_promot="True")
            promoted = True

    if request.method == "POST":
        form = PickerForm(request.POST)
        if form.is_valid():
                data = form.cleaned_data

        return HttpResponseRedirect(reverse('restaurants', args=[data['city'], data['category']]))

    context = {
    	'city': city.capitalize(),
        'category': human_category,
        'restaurants': restaurants_by_city,
        'promoted': promoted,
        'viewedrestaurants': viewedrestaurants,
        'form': PickerForm(label_suffix='', initial={'category': 'Medi', 'city': 'barcelona'})
    }

    return render(request, 'forkilla/restaurants.html', context)

def restaurant(request, restaurant_number=""):

    viewedrestaurants = _check_session(request)

    if request.method == "POST":
        if request.user.is_authenticated:
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.user = request.user
                review.restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
                review.save()
                request.session["review"] = review.id
                request.session["result"] = "OK"
            else:
                request.session["result"] = form.errors
            return HttpResponseRedirect(reverse('restaurant', args=[restaurant_number]))
        else:
            return HttpResponseRedirect('/login?next=/restaurant/' + restaurant_number)

    elif request.method == "GET":
        try:
            restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
            lastviewed = RestaurantInsertDate(viewedrestaurants=viewedrestaurants, restaurant=restaurant)

            lastviewed.save()
        except Restaurant.DoesNotExist:
            return render(request, 'forkilla/404.html')

        categories = Restaurant._d_categories

        reviews = []
        try:
            reviews = Review.objects.filter(restaurant=restaurant)
        except Review.DoesNotExist:
            reviews = []

        context = {
            'form': ReviewForm(),
        	'restaurant': restaurant,
            'reviews': reviews,
            'viewedrestaurants': viewedrestaurants
        }

    return render(request, 'forkilla/details.html', context)

@login_required
def reservation(request):

    viewedrestaurants = _check_session(request)
    categories = Restaurant._d_categories

    try:
        if request.method == "POST":
            form = ReservationForm(request.POST)
            if form.is_valid():
                resv = form.save(commit=False)

                #We set the user
                resv.user = request.user

                #Set the restaurant
                restaurant_number = request.session["reserved_restaurant"]
                resv.restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)

                #check if the restaurant has enough room
                reservations = Reservation.objects.filter(restaurant=resv.restaurant, time_slot = resv.time_slot)
                resv_current_people = 0
                for reservation in reservations:
                    resv_current_people += reservation.num_people

                if (resv.restaurant.capacity < (resv_current_people + resv.num_people)):
                    request.session["result"] = "FAIL"
                    request.session["restaurant"] = restaurant_number
                else:
                    resv.save()
                    request.session["reservation"] = resv.id
                    request.session["result"] = "SUCCESS"

            else:
                request.session["result"] = form.errors
            return HttpResponseRedirect(reverse('checkout'))

        elif request.method == "GET":

            restaurant_number = request.GET["reservation"]
            restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
            request.session["reserved_restaurant"] = restaurant_number

            form = ReservationForm()

            context = {
                'restaurant': restaurant,
                'viewedrestaurants': viewedrestaurants,
                'form': form
            }

    except Restaurant.DoesNotExist:
        return HttpResponse("Restaurant Does not exist")

    return render(request, 'forkilla/reservation.html', context)

@login_required
def reservations(request):

    viewedrestaurants = _check_session(request)
    reservations = Reservation.objects.filter(user=request.user)

    context = {
        'reservations': reservations,
        'viewedrestaurants': viewedrestaurants
    }

    return render(request, 'forkilla/reservations.html', context)


def checkout(request):

    viewedrestaurants = _check_session(request)

    if request.session["result"] == "SUCCESS":
        reservation = Reservation.objects.get(id=request.session["reservation"])
        time = Reservation._d_slots.get(reservation.time_slot)
    else:
        return HttpResponseRedirect('/reservation?reservation=' + request.session["restaurant"])

    context = {
        'success': request.session["result"],
        'reservation': reservation,
        'time': time,
        'viewedrestaurants': viewedrestaurants,
    }

    return render(request, 'forkilla/checkout.html', context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=new_user.username, password=raw_password)
            auth.login(request, user)

            return HttpResponseRedirect(reverse('index'))
    else:
        form = UserCreationForm()

    context = {
        'form': form
    }

    return render(request, 'forkilla/register.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None and user.is_active:
                # Correct password, and the user is marked "active"
                auth.login(request, user)
                # Redirect to a success page.
                if request.GET.get('next'):
                    return HttpResponseRedirect(request.GET['next'])
                else:
                    return HttpResponseRedirect(reverse('index'))
            else:
                # Show an error page
                return 0
    else:
        form = AuthenticationForm()

    context = {
        'form': form
    }

    return render(request, 'forkilla/login.html', context)

def comparator(request, ips):

    viewedrestaurants = _check_session(request)

    if request.method == "POST":
        form = ComparatorForm(request.POST)
        if form.is_valid():
            data = "?city=" + form.cleaned_data.get('city') + "&category=" + form.cleaned_data.get('category') + "&price_average=" + str(form.cleaned_data.get('price_average'))

    else:
        form = ComparatorForm()
        data = None

    context = {
        'form': form,
        'data': data,
        'urls': ips,
        'viewedrestaurants': viewedrestaurants
    }

    return render(request, 'forkilla/comparator.html', context)

def _login(request, user):

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = authenticate(username=username, password=password)

    if user is not None and user.is_active:
        # Correct password, and the user is marked "active"
        auth.login(request, user)

forkilla/templates/forkilla/base.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Forkilla</title>
  <meta name="description" content="Forkilla">
  <meta name="author" content="Pedro Pizarro, Lluís Montabes">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.min.css' %}" />
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Sree+Krushnadevaraya&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cutive+Mono&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

</head>

<body>

  <script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>

  {% block navigation %}
  <div class="navigation-wrap" id="navigation">
    <div class="content">
      <a href="{% url 'index' %}">
      <div class="logo">
        Forkilla
      </div>
      </a>
    </div>
  </div>
  {% endblock %}

  {% block header %}
  {% endblock %}

  <div class="page">

    <div class="area">
      <div class="content">

        {% block content %}
        {% endblock %}

        {% block last-viewed %}
        <div class="last-viewed">
          <div class="shade"></div>

          <h3>Recently viewed restaurants</h3>

          {% if viewedrestaurants.restaurantinsertdate_set.all %}
            {% for r in viewedrestaurants.restaurantinsertdate_set.all|slice:"5" %}

              <div class="card small">
                <a href="{% url 'restaurant' r.restaurant.restaurant_number%}">
                  <div class="restaurant-image" style="background-image: url('{{r.restaurant.featured_photo.url}}')"></div>
                  <div class="content">
                    <div class="title">
                      {{r.restaurant.name}}
                    </div>
                    <div class="subtitle">
                      {{r.restaurant.city}}, {{r.restaurant.get_human_category}}
                    </div>
                  </div>
                </a>
              </div>

          {% endfor %}
        {% else %}

          <div style="margin: 1.5em; opacity: .75">
            You have no recently viewed restaurants.<br />Once you check out a restaurant, it will appear here.
          </div>

        {% endif %}

        </div>
        {% endblock %}

      </div>
    </div>
  </div>

  {% block user %}
  <div class="floating" id="user">
    {% if user.is_authenticated %}
      <div class="top">
        Welcome, <b>{{user}}</b>!
      </div>
      <div class="bottom">
        <a href="{% url 'comparator' %}">Comparator</a>
      </div>
      <div class="bottom">
        <a href="{% url 'reservations' %}">Your reservations</a>
      </div>
      <div class="bottom">
        <a href="{% url 'logout' %}">Log out</a>
      </div>
    {% else %}
      <div class="top">
        <i class="fas fa-user"></i>
      </div>
      <div class="bottom">
        <a href="{% url 'register' %}">Register</a> or <a href="{% url 'login' %}">log in</a>
      </div>
    {% endif %}
  </div>
  {% endblock %}

  <script>

  $(document).scroll(function(e){

    $("#header-content").css("transform", "translateY(" + (-$(document).scrollTop() / 15) + "px)");

    if ($(document).scrollTop() > $("#header-logo").offset().top + $("#header-logo").outerHeight()) {

      $("#nav-logo").removeClass("hidden");

      if ($(document).scrollTop() > $(".header").outerHeight()) {
        $("#navigation").removeClass("hidden");
      } else {
        $("#navigation").addClass("hidden");
      }

    } else {
      //$("#nav-logo").addClass("hidden");
      //$("#navigation").css("padding-top", 0);
    }
  });

  function scrollToTop() {
    $("html, body").animate({ scrollTop: 0 }, 200);
  }

  </script>

  {% block extra_js %}
  {% endblock %}

</body>
</html>

forkilla/templates/forkilla/checkout.html
{% extends 'forkilla/base.html' %}

{% block navigation %}
{% endblock %}

{% block header %}
<div class="header restaurant" id="header" style="background-image: url('{{reservation.restaurant.featured_photo.url}}')">
  <div class="logo" id="header-logo">

  </div>
</div>
{% endblock %}
{% block content %}

<div class="trail">
  <div class="content">
    <a href="{% url 'index' %}">forkilla</a> >

    <a href="{% url 'restaurants' %}{{reservation.restaurant.city}}">{{reservation.restaurant.city}}</a>
    > <a href="{% url 'restaurants' %}{{reservation.restaurant.city}}/{{reservation.restaurant.category}}">{{reservation.restaurant.get_human_category}}</a>
    > <a href="{% url 'restaurant' reservation.restaurant.restaurant_number%}">{{reservation.restaurant.name}}</a>
    > <b>Checkout</b>
  </div>
</div>

<div class="text-body">

    <h2 style="margin: 0">Your reservation was placed successfully!</h2><br>
    <div class="reservation">
      <div class="hole"></div>
      <div class="photo" style="background-image: url('{{reservation.restaurant.featured_photo.url}}')"></div>
      <div class="content">
        <b>{{reservation.restaurant.name}}</b><br />
        <b>{{time}}</b><br /><br />
        {{reservation.num_people}} person{% if reservation.num_people > 1 %}s{% endif %}
      </div>
    </div>

</div>
{% endblock content %}

forkilla/templates/forkilla/comparator.html
{% extends 'forkilla/base.html' %}

{% block content %}

<div class="trail">
  <div class="content">
    <a href="{% url 'index' %}">forkilla</a> > <b>Comparator</b>
  </div>
</div>

<div class="text-body">

  <h2 style="margin: 0">Comparator</h2>

  <form class="comparator-form" id="comparator-form" method="POST">
      {% csrf_token %}
      {{ form.as_table }}
      <button type="submit" class="button inverted light-shadow"><i class="fas fa-check"></i> Confirm</button>
  </form>

</div>

{% if data %}
<div id="results">

</div>
{% endif %}

<div style="display: none" id="card-dummy">
  <div class="card">
    <a id="restaurant-link" href="">
      <div id="restaurant-image" class="restaurant-image">
        <button type="submit" class="button opaque" id="reservation-button" name="reservation" value="">
          <i class="fas fa-utensils"></i> Place reservation
        </button>
      </div>
      <div class="content">
        <div class="title" id="restaurant-title">
          {{restaurant.name}}
        </div>
        <div class="subtitle" id="restaurant-subtitle">
          {{restaurant.city}}, {{restaurant.get_human_category}}
        </div>
        <div class="description" id="restaurant-description">
          {{restaurant.menu_description}}
        </div>
        <div class="price">
          User ratings:<br /><span style="font-size: 24px" id="restaurant-rating">{{restaurant.rate}}</span> / 10<br /><br />Average price:<br /><span style="font-size:24px" id="restaurant-price">{{restaurant.price_average}}</span> €
        </div>
      </div>
    </a>
  </div>
</div>

{% endblock content %}

{% if data %}
  {% block extra_js %}
  <script type="text/javascript">

    urls = {{urls|safe}};

    urls.forEach(function(url) {

      $.get('http://' + url + '/api/restaurants/{{data}}&format=json', function(response) {

        $("#results").append("<h2>" + url + "</h2>");
        restaurants = response.results;

        restaurants.forEach(function(r){
          console.log(r);
          $("#card-dummy #restaurant-link").attr("href", "/forkilla/restaurant/" + r.restaurant_number);
          $("#card-dummy #restaurant-image").css("background-image", "url('" + r.featured_photo + "')");
          $("#card-dummy #restaurant-title").html(r.name);
          $("#card-dummy #restaurant-subtitle").html(r.city + ", " + r.category);
          $("#card-dummy #restaurant-description").html(r.menu_description);
          $("#card-dummy #restaurant-rating").html(r.rate);
          $("#card-dummy #restaurant-price").html(r.price_average);
          $("#results").append($("#card-dummy").html());
        });
      });
    });

  </script>
  {% endblock %}
{% endif %}

forkilla/templates/forkilla/details.html
{% extends 'forkilla/base.html' %}

{% block navigation %}
{% endblock %}

{% block header %}
<div class="header restaurant" id="header" style="background-image: url('{{restaurant.featured_photo.url}}')">
  <div class="logo" id="header-logo">

  </div>
</div>
{% endblock %}

{% block content %}

<div class="trail">
  <div class="content">
    <a href="{% url 'index' %}">forkilla</a> >

    <a href="{% url 'restaurants' %}{{restaurant.city}}">{{restaurant.city}}</a>
    > <a href="{% url 'restaurants' %}{{restaurant.city}}/{{restaurant.category}}">{{restaurant.get_human_category}}</a>
    > <b>{{restaurant.name}}</b>
  </div>
</div>

<div class="text-body restaurant-details">
  <div class="title">
    {{restaurant.name}}
  </div>
  <div class="subtitle">
    {{restaurant.address}}
  </div>
  <div class="details">
    {{restaurant.city}}, {{restaurant.country}} · {{restaurant.get_human_category}}
  </div>
  <div class="description">
    {{restaurant.menu_description}}
  </div>
  <div class="stats">
    <div class="stat">
      User ratings:<br /><span style="font-size: 32px">{{restaurant.rate}}</span> / 10
    </div>
    <div class="stat">
      Average price:<br /><span style="font-size: 32px">{{restaurant.price_average}}</span> €
    </div>
  </div>

</div>

<form action="{% url 'reservation'%}" method="get">
  <div class="text-body">
    <button type="submit" class="button inverted" name="reservation" value={{restaurant.restaurant_number}}>
      <i class="fas fa-utensils"></i> Place reservation
    </button>
  </div>
</form>

<h2>Our users' opinions:</h2>

<div class="text-body reviews">

  {% if reviews %}
    {% for review in reviews %}
      <div class="review" style="margin-bottom: 1em">
      <b>{{review.user}} says:</b><br>
      {{review.message}}<br>
      <div style="opacity: 1; font-size: 14px; background: #c44569; padding: .1em .25em; color: white; margin: .5em 0; display: inline-block"><b>{{review.rating}}</b> / 5</div>
      </div>
    {% endfor %}
  {% else %}
    There are no reviews yet. Have you been here? Tell us your opinion!
  {% endif %}

</div>

<h2>Leave a review</h2>

<form class="register-form" style="margin-left: 2em" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="button opaque">Publish review</button>
</form>

{% endblock %}

forkilla/templates/forkilla/index.html
{% extends 'forkilla/base.html' %}

{% block header %}
<div class="header standard" id="header">

  <div class="middle" id="header-content">
    <div class="logo" id="header-logo">
      Forkilla
    </div>
    <div class="inline" id="picker">
      <form class="picker" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button light-shadow"><i class="fas fa-arrow-right"></i></button>
      </form>
    </div>
  </div>

</div>
{% endblock %}

{% block navigation %}
{% endblock %}

{% block content %}

<div class="trail">
  <div class="content">
    <a href="{% url 'index' %}">forkilla</a> > <b>Promoted</b>
  </div>
</div>
<h2>Today's featured</h2>

  {% if restaurants %}

  <form action="{% url 'reservation'%}" method="get">
    {% for restaurant in restaurants %}

      <div class="card">
        <a href="{% url 'restaurant' restaurant.restaurant_number%}">
          <div class="restaurant-image" style="background-image: url('{{restaurant.featured_photo.url}}')">
            <button type="submit" class="button opaque" id="reservation-button" name="reservation" value={{restaurant.restaurant_number}}>
              <i class="fas fa-utensils"></i> Place reservation
            </button>
          </div>
          <div class="content">
            <div class="title">
              {{restaurant.name}}
            </div>
            <div class="subtitle">
              {{restaurant.city}}, {{restaurant.get_human_category}}
            </div>
            <div class="description">
              {{restaurant.menu_description}}
            </div>
            <div class="price">
              User ratings:<br /><span style="font-size: 24px">{{restaurant.rate}}</span> / 10<br /><br />Average price:<br /><span style="font-size:24px">{{restaurant.price_average}}</span> €
            </div>
          </div>
        </a>
      </div>

    {% endfor %}
  </form>

  {% else %}
    <div class="text-body">
        <p>No restaurants are available.</p>
    </div>
  {% endif %}
{% endblock %}